### ISSUE TITLE
Installation of alephclient fails on fresh Ubuntu 20.04

### ISSUE THREAD

**Issue by critocrito** [alephdata/alephclient#18]
Following the installation instructions for `alephclient` on a fresh Ubuntu 20.04 I get the following error:

```
$ python3 -m venv my-project-env
$ source my-project-env/bin/activate
(my-project-env) $ pip install alephclient
Collecting alephclient
  Downloading alephclient-2.0.3-py2.py3-none-any.whl (13 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 3.6 MB/s
Collecting banal>=1.0.1
  Downloading banal-1.0.1-py2.py3-none-any.whl (5.3 kB)
Collecting requests>=2.21.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 802 kB/s
Collecting requests-toolbelt>=0.9.1
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 4.4 MB/s
Collecting click>=7.0
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.8 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 7.2 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.1 MB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 7.1 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 6.7 MB/s
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/crito/my-project-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-obajncoq/pyyaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-obajncoq/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tzz6gpkm
       cwd: /tmp/pip-install-obajncoq/pyyaml/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
Failed to build pyyaml
Installing collected packages: pyyaml, banal, certifi, idna, chardet, urllib3, requests, requests-toolbelt, click, alephclient
    Running setup.py install for pyyaml ... done
Successfully installed alephclient-2.0.3 banal-1.0.1 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 idna-2.10 pyyaml-5.3.1 requests-2.24.0 requests-toolbelt-0.9.1 urllib3-1.25.10
```

Repeating the same steps and installing `wheel` before `alephclient` removes the above error.

```
$ python3 -m venv alephclient
$ source alephclient/bin/activate
(alephclient) $ pip install wheel
Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: wheel
Successfully installed wheel-0.35.1
(alephclient) $ pip install alephclient
Collecting alephclient
  Using cached alephclient-2.0.3-py2.py3-none-any.whl (13 kB)
Collecting requests>=2.21.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting banal>=1.0.1
  Using cached banal-1.0.1-py2.py3-none-any.whl (5.3 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting click>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting requests-toolbelt>=0.9.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=44619 sha256=602ab9277e57d0863f63236e7e6d508bb0345316ed722524a16001a980d6038e
  Stored in directory: /home/crito/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
Successfully built pyyaml
Installing collected packages: certifi, urllib3, chardet, idna, requests, banal, pyyaml, click, requests-toolbelt, alephclient
Successfully installed alephclient-2.0.3 banal-1.0.1 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 idna-2.10 pyyaml-5.3.1 requests-2.24.0 requests-toolbelt-0.9.1 urllib3-1.25.10
```

But running `alephclient` results in a runtime error:

```
(alephclient) $ alephclient -h
Traceback (most recent call last):
  File "/home/crito/alephclient/bin/alephclient", line 5, in <module>
    from alephclient.cli import cli
  File "/home/crito/alephclient/lib/python3.8/site-packages/alephclient/cli.py", line 6, in <module>
    from alephclient.api import AlephAPI
  File "/home/crito/alephclient/lib/python3.8/site-packages/alephclient/api.py", line 7, in <module>
    from six.moves.urllib.parse import urlencode, urljoin
ModuleNotFoundError: No module named 'six'
```

Manually installing `six` with a `pip install six` resolves the issue.

**Comment by sunu** [comment]
Thanks for the report! We should get rid of `six` since Python 2 is no more now
